nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-docker-build.cjs
    spec: 'https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-docker-build.js'
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: 'https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js'

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  'vite@*':
    dependencies:
      'supports-color': '*'
  'local-pkg@*':
    dependencies:
      '@vueuse/core': '*'
      'vue': '*'
      'preact': '*'
  '@ckeditor/ckeditor5-vue@*':
    dependencies:
      'vue': '3.*'
