version: '3.9'
services:
  db:
    image: postgres:13

    working_dir: /

    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./data:/data
    networks:
      - default
    command: postgres -c logging_collector=on -c log_destination=stderr -c
      log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=60 -c
      log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M

  minio:
    image: minio/minio
    restart: unless-stopped
    volumes:
      - minio-data:/data
    environment:
      - MINIO_BROWSER_REDIRECT_URL=http://console.media.${DOMAIN}
    working_dir: /work
    networks:
      - default
    command: server --console-address ":9001" /data

  imgproxy:
    image: darthsim/imgproxy:latest
    healthcheck:
      test: ['CMD', 'imgproxy', 'health']
    networks:
      - default
    environment:
      PORT: 8080
      # IMGPROXY_LOG_LEVEL: "warn"
      # IMGPROXY_ENABLE_DEBUG_HEADERS: "false"
      # IMGPROXY_DEVELOPMENT_ERRORS_MODE: "false"
      # IMGPROXY_REPORT_DOWNLOADING_ERRORS: "false"
      IMGPROXY_MAX_SRC_RESOLUTION: 50
      IMGPROXY_MAX_SRC_FILE_SIZE: 20971520 # 20MB
      IMGPROXY_TTL: 352800 # client-side cache time is 1 week
      IMGPROXY_FORMAT_QUALITY: 'jpeg=80,webp=70,avif=50'
      # IMGPROXY_SIGNATURE_SIZE: 32
      IMGPROXY_USE_S3: 'true'
      IMGPROXY_S3_REGION: 'test'
      IMGPROXY_S3_ENDPOINT: 'http://minio:9000'

  nginx:
    image: nginx:alpine

    networks:
      - default


networks:
  default:
    # No metadata required right now.

volumes:
  # Postgres' data
  db-volume:

  # minio data
  minio-data:
