version: '3.9'
services:
  db:
    restart: unless-stopped
    ports:
      - '6543:5432'
    env_file:
      - docker/.env
  minio:
    restart: unless-stopped
    env_file:
      - docker/.env
  imgproxy:
    restart: unless-stopped
    env_file:
      - .env

  nginx:
    image: nginx:alpine

    volumes:
      - nginx_cache:/var/cache/nginx

      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/10-default.conf:/etc/nginx/conf.d/10-default.conf
      - ./docker/nginx/20-proxy.conf:/etc/nginx/conf.d/20-proxy.conf

      - ./docker/nginx/40-server.conf:/etc/nginx/templates/40-server.conf.template
      - ./docker/nginx/30-img.conf:/etc/nginx/templates/30-img.conf.template
      - ./docker/nginx/30-media.conf:/etc/nginx/templates/30-media.conf.template

    ports:
      - "8000:80"

    restart: unless-stopped

  server:
    image: smil-server

    networks:
      - default

    env_file:
      - .env
    environment:
      PORT: 5678

    depends_on:
      - db
      - minio
      - imgproxy
      - nginx

    restart: unless-stopped

    # entrypoint: yarn exec ash
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t

volumes:
  nginx_cache:
