version: '3.9'
services:
  db:
    ports:
      - '6543:5432'
    env_file:
      - docker/.env
  minio:
    env_file:
      - docker/.env
  imgproxy:
    env_file:
      - .env

  nginx:
    image: nginx:alpine

    volumes:
      - nginx_cache:/var/cache/nginx

      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/10-default.conf:/etc/nginx/conf.d/10-default.conf
      - ./docker/nginx/20-proxy.conf:/etc/nginx/conf.d/20-proxy.conf

      - ./docker/nginx/40-dev.conf:/etc/nginx/templates/40-dev.conf.template
      - ./docker/nginx/30-img.conf:/etc/nginx/templates/30-img.conf.template
      - ./docker/nginx/30-media.conf:/etc/nginx/templates/30-media.conf.template

    ports:
      - '12345:12345'
      - "80:80"

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SETUP_MODE: dev

    env_file:
      - docker/.env
    environment:
      PORT: 5678

    volumes:
      - .:/work

      # let's us run docker & docker-compose from inside container (used for yarn setup)
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock
      - nm_root:/work/node_modules
      - nm_app_client:/work/@app/client/node_modules
      - nm_app_config:/work/@app/config/node_modules
      - nm_app_db:/work/@app/db/node_modules
      - nm_app_graphql:/work/@app/graphql/node_modules
      - nm_app_server:/work/@app/server/node_modules
      - nm_app_editor:/work/@app/editor/node_modules
      - vscode_extensions:/root/.vscode-server

    working_dir: /work
    networks:
      - default
    ports:
      # Node `--inspect=...` port numbers for debugging
      - '9678:9678'
      - '9876:9876'
      - '9757:9757'
    depends_on:
      - db
      - minio
      - nginx
      - imgproxy
    command: sleep infinity

volumes:
  nm_root:
  nm_app_client:
  nm_app_config:
  nm_app_db:
  nm_app_graphql:
  nm_app_server:
  nm_app_editor:
  vscode_extensions:
  nginx_cache:
