REVOKE ALL ON SCHEMA public FROM public;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM public;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON FUNCTIONS FROM public;
GRANT ALL ON SCHEMA public TO :DATABASE_OWNER;
