// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    _TransistionExpand: typeof import('./components/_TransistionExpand.vue')['default']
    Calendar: typeof import('./components/Calendar.vue')['default']
    EventCalendar: typeof import('./components/EventCalendar.vue')['default']
    EventWidget: typeof import('./components/EventWidget.vue')['default']
    ExpandTransition: typeof import('./components/ExpandTransition.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    IconCarbonBee: typeof import('~icons/carbon/bee')['default']
    IconCarbonMenu: typeof import('~icons/carbon/menu')['default']
    IconFontelicoEmoDevil: typeof import('~icons/fontelico/emo-devil')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconMdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    IconMdiClockTimeFiveOutline: typeof import('~icons/mdi/clock-time-five-outline')['default']
    IconMdiEmoticonHappyOutline: typeof import('~icons/mdi/emoticon-happy-outline')['default']
    IconMdiMenu: typeof import('~icons/mdi/menu')['default']
    IconMdiTranslate: typeof import('~icons/mdi/translate')['default']
    IconSmilIcon: typeof import('~icons/smil/icon')['default']
    IconSmilLogo: typeof import('~icons/smil/logo')['default']
    IconSmilLogoAarhus: typeof import('~icons/smil/logo-aarhus')['default']
    IconSmilTest: typeof import('~icons/smil/test')['default']
    Lang: typeof import('./components/Lang.vue')['default']
    LocaleSwitcher: typeof import('./components/LocaleSwitcher.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    NavToggleButton: typeof import('./components/NavToggleButton.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverGroup: typeof import('@headlessui/vue')['PopoverGroup']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    SiteNav: typeof import('./components/SiteNav.vue')['default']
    SiteNavLink: typeof import('./components/SiteNavLink.vue')['default']
    TransistionExpand: typeof import('./components/TransistionExpand.vue')['default']
  }
}

export { }
